accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='accounts:login'), name='logout'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='user_profile'),
]

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('add/', views.PostCreateView.as_view(), name='add'),
    path('all/', views.MyPostListView.as_view(), name='my_list'),
    path('all/<slug:slug>/', views.post_detail_view, name='detail'),
    path('<slug:slug>/', views.post_detail_view, name='detail'),
    # path('all/<slug:slug>/', views.PostDetailView.as_view(), name='detail'),
    path('<slug:slug>/add-comment/', views.CommentCreateView.as_view(), name='add_comment'),
    path('<slug:slug>/edit/', views.PostUpdateView.as_view(), name='edit'),
    path('<slug:slug>/remove/', views.PostDeleteView.as_view(), name='remove'),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(User):
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    phoneNumber = models.CharField(max_length=10, blank=True)

    def __str__(self):
        return self.username

posts/models.py
from django.db import models
from accounts.models import UserProfile
from django.utils import timezone
from autoslug import AutoSlugField


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    post_image = models.ImageField(blank=True, upload_to='post_pics')
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    created_date = models.DateField(default=timezone.now)
    slug = AutoSlugField(populate_from='title')

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.CharField(max_length=250, verbose_name='Comment')
    created_date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:10]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from accounts.models import UserProfile


class UserProfileCreationForm(UserCreationForm):
    class Meta:
        model = UserProfile
        fields = ('username', 'email', 'first_name', 'last_name',
                  'password1', 'password2', 'phoneNumber', 'profile_pic')

posts/forms.py
from django import forms
from posts.models import Post, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'created_date', 'post_image')

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView
from django.contrib.messages.views import SuccessMessageMixin
from accounts.forms import UserProfileCreationForm, UserProfile
from django.urls import reverse_lazy


class UserCreateView(SuccessMessageMixin, CreateView):
    model = UserProfile
    form_class = UserProfileCreationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('accounts:login')

    def get_success_message(self, cleaned_data):
        return self.object.username + ' registration completed successfully'


class UserDetailView(DetailView):
    model = UserProfile
    context_object_name = 'user_profile'

posts/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.forms import PostForm, CommentForm, Post, Comment
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseForbidden, HttpResponseRedirect, Http404


def index(request):
    posts = get_list_or_404(Post)
    return render(request, 'index.html', {'posts': posts})


class PostCreateView(SuccessMessageMixin, CreateView, LoginRequiredMixin):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('posts:my_list')
    template_name = 'posts/post_form.html'
    # success_message = "Post was created successfully"

    def get_success_message(self, cleaned_data):
        return self.object.title+" added successfully"

    def form_valid(self, form):
        form.instance.author = self.request.user.userprofile
        return super().form_valid(form)


class PostUpdateView(SuccessMessageMixin, UpdateView, LoginRequiredMixin):
    model = Post
    form_class = PostForm

    def get_success_url(self):
        return reverse_lazy('posts:detail', kwargs={'slug': self.object.slug})

    def get_success_message(self, cleaned_data):
        return self.object.title+' updated successfully'


class PostDeleteView(DeleteView, LoginRequiredMixin):
    model = Post
    context_object_name = 'post'
    success_url = reverse_lazy('posts:my_list')


class MyPostListView(ListView):
    model = Post
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user.userprofile)


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    extra_context = {'comment_form': CommentForm}


# ClassBasedView for Post-Comment system
# All functions and algorithms similar to Function Based View
# You will better understand this version if you try to implement FBV
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm

    def get_success_url(self):
        return reverse_lazy('posts:detail', kwargs={'slug': self.object.post.slug})

    def form_valid(self, form):
        post = get_object_or_404(Post, slug=self.kwargs['slug'])
        form.instance.post = post
        form.instance.author = self.request.user.userprofile
        return super().form_valid(form)


# This post-comment implementation using FunctionBasedViews
# It's simpler but in overall similar to ClassBasedImplementation
def post_detail_view(request, slug):
    post = Post.objects.get(slug=slug)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            form.instance.post = post
            form.instance.author = request.user.userprofile
            form.save(commit=True)
            reverse_lazy('posts:detail', kwargs={'slug': slug})

    form = CommentForm()
    return render(request, 'posts/detail.html', {'post': post, 'form': form})

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="alert-success">
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
    </div>
    <h1>Login:</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-primary" type="submit" value="Login">
        <input type="hidden" name="next" value={% url 'posts:my_list' %}>
    </form>
    <p>If you don't have an account, please click <a href="{% url 'accounts:register' %}">here</a> to register</p>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <h1>Registration Form:</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="ui button positive" type="submit" value="Register">
    </form>
{% endblock %}

accounts/templates/accounts/userprofile_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="ui card">
        <div class="image">
            <img src="{{ user_profile.profile_pic.url }}">
        </div>
        <div class="content">
            <a class="header">{{ user_profile.get_full_name }}</a>
            <div class="meta">
                <span class="date">{{ user_profile.date_joined }}</span>
            </div>
        </div>
        <div class="extra content">
            <a>
                <i class="pencil alternate icon"></i>
                Post number: {{ user_profile.post_set.count }}
            </a>
        </div>
    </div>
{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% block content %}
    {% if messages %}
        <div class="alert alert-success">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}
    <div class="ui items">
        <div class="item">
            <a class="ui small image">
                <img src="{{ post.post_image.url }}" alt="">
            </a>
            <div class="content">
                <a class="header">{{ post.title }}</a>
                <div class="description">
                    <p>{{ post.content }}</p>
                </div>
                <div class="extra">
                    <p>{{ post.created_date }} by {{ post.author.get_full_name }}</p>
                    {% if post.author == user.userprofile %}
                        <div class="ui two buttons">
                            <a href="{% url 'posts:edit' slug=post.slug %}">
                                <div class="ui basic green button">Edit</div>
                            </a>
                            <a href="{% url 'posts:remove' slug=post.slug %}">
                                <div class="ui basic red button">Remove</div>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="ui comments">
        <h3 class="ui dividing header">Comments</h3>
        {% for comment in post.comment_set.all %}
            <div class="comment">
                <a class="avatar">
                    <img src="{{ comment.author.profile_pic.url }}" alt="">
                </a>
                <div class="content">
                    <a href="{% url 'accounts:user_profile' pk=comment.author.pk %}" class="author">{{ comment.author.get_full_name }}</a>
                    <div class="metadata">
                        <span class="date">{{ comment.created_date }}</span>
                    </div>
                    <div class="text">
                        {{ comment.text }}
                    </div>
                </div>
            </div>
        {% endfor %}
        <form class="ui reply form" method="post">
            {% csrf_token %}
            <div class="field">
                {{ form.as_p }}
            </div>
            <div class="ui blue labeled submit icon button">
                <i class="icon edit"></i>
                <input style="color: white" type="submit" value="Send" class="btn">
            </div>
        </form>
    </div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure to want to delete <b>{{ post }}</b>?</p>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <img style="width: 250px;" src="{{ post.post_image.url }}" alt="">
        <h3>{{ post.title }}</h3>
        <p>{{ post.content }}</p>
        <p><small><b>{{ post.created_date }}</b> by <b>{{ post.author }}</b></small></p>
    </div>
    <div class="jumbotron">
        <h2>Comments:</h2>
        {% for comment in post.comment_set.all %}
            <p>{{ comment.text }}</p>
            <p>{{ comment.created_date }} by {{ comment.author }}</p>
        {% empty %}
            <p>No Comments here yet</p>
        {% endfor %}
    </div>
    <div>
        <form method="post" action="{% url 'posts:add_comment' slug=post.slug %}">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <input type="submit" value="Send">
        </form>
    </div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    {% if form.instance.pk %}
        <h2>Update Post</h2>
    {% else %}
        <h1>Add Post</h1>
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}
{% block content %}
    {% if messages %}
        <div class="alert alert-success">
            {% for message in messages %}
                <b>{{ message }}</b>
            {% endfor %}
        </div>
    {% endif %}
    <h1>My Posts:</h1>
    <div class="ui items">
        {% for post in posts %}
            <div class="item">
                <div class="ui tiny image">
                    <img src="{{ post.post_image.url }}">
                </div>
                <div class="middle aligned content">
                    <a href="{{ post.slug }}" class="header">{{ post.title }}</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Social</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">Social</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'posts:my_list' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:add' %}">Add Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h2 class="ui center aligned icon header">
        <i class="circular coffee icon"></i>
        Social Posts
    </h2>
    <div class="row">
        {% for post in posts %}
            <div style="margin: 10px 0;" class="col-lg-4">
                <div class="ui raised card">
                    <div class="ui image">
                        <img style="" src="{{ post.post_image.url }}" alt="">
                    </div>
                    <div class="content">
                        <a href="{% url 'posts:detail' slug=post.slug %}">
                            <div class="header">{{ post.title }}</div>
                        </a>
                    </div>
                    <div class="extra content">
                        <div class="right floated author">
                            <img class="ui avatar image" src="{{ post.author.userprofile.profile_pic.url }}">
                            {{ post.author.get_full_name }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}